// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDM9MVqExZZb-4ymom5ttUdgOoeQzELc',
    appId: '1:811838786938:web:d41d26fd7dad68e84f9ac3',
    messagingSenderId: '811838786938',
    projectId: 'arenaflow-2db49',
    authDomain: 'arenaflow-2db49.firebaseapp.com',
    storageBucket: 'arenaflow-2db49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrLdIQlkjQsljoi3zYHhbmLHxDQK-1v4',
    appId: '1:811838786938:android:68adfbbc2920d3734f9ac3',
    messagingSenderId: '811838786938',
    projectId: 'arenaflow-2db49',
    storageBucket: 'arenaflow-2db49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1-CXt0UIinPaGdy76OIVrsD_Xk7_Zcbw',
    appId: '1:811838786938:ios:6d4ce7438f1aa9124f9ac3',
    messagingSenderId: '811838786938',
    projectId: 'arenaflow-2db49',
    storageBucket: 'arenaflow-2db49.firebasestorage.app',
    iosBundleId: 'com.example.arenaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1-CXt0UIinPaGdy76OIVrsD_Xk7_Zcbw',
    appId: '1:811838786938:ios:6d4ce7438f1aa9124f9ac3',
    messagingSenderId: '811838786938',
    projectId: 'arenaflow-2db49',
    storageBucket: 'arenaflow-2db49.firebasestorage.app',
    iosBundleId: 'com.example.arenaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhDM9MVqExZZb-4ymom5ttUdgOoeQzELc',
    appId: '1:811838786938:web:98e7872d27134aa64f9ac3',
    messagingSenderId: '811838786938',
    projectId: 'arenaflow-2db49',
    authDomain: 'arenaflow-2db49.firebaseapp.com',
    storageBucket: 'arenaflow-2db49.firebasestorage.app',
  );
}
